name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y emacs
        
    - name: Run lint
      run: make lint

    - name: Run test
      run: make test
